### ISSUE TITLE
Update assessment utility to adapt to Q4 C2M2 changes

### ISSUE THREAD

**Issue by lliming** [nih-cfde/c2m2-assessment#2]

**Comment by lliming** [comment]
@u8sand Anything to report here? Thanks.

**Comment by u8sand** [comment]
To my knowledge, no adjustments are necessary unless new metrics are being proposed to assess new metadata elements. If new metrics are proposed, added and adequately described in the metrics table (https://docs.google.com/spreadsheets/d/1VZWkKwvJ0AdgUThvKU7NVhWigtvKjF0aXe9ywSTlfxc/edit#gid=0) then we'll know what work needs to be done.

**Comment by lliming** [comment]
It looks like several new metrics were added to the Google Sheet sometime recently (not sure when). Specifically, rows 50-61 (IDs cfde_fair:33-44). Are those all being computed and reported by the tool now? If so, we're probably all set. If not, any update on how that's going?

**Comment by RLC-DCPPC** [comment]
Hi @u8sand, @lliming . Are we good here?

**Comment by u8sand** [comment]
I believe @mschor worked on the new metrics and added them in this commit https://github.com/nih-cfde/c2m2-assessment/commit/ddb9bc46933dc323e6c30ac57af5df67ada1e328 the ids/name/descriptions might not be quite right however.

**Comment by u8sand** [comment]
I finalized what @mschor did so this should now be ready as far as I'm aware
