### ISSUE TITLE
Update assessment utility to use controlled vocabulary of metrics stored in Deriva

### ISSUE THREAD

**Issue by lliming** [nih-cfde/c2m2-assessment#3]
Once the vocabulary table described in https://github.com/nih-cfde/cfde-deriva/issues/310 has been populated with specific entries for specific FAIRness metrics, the assessment tool needs to be modified to use the metric identifiers in the vocabulary table to avoid any confusion about which metric is which.

**Comment by lliming** [comment]
@u8sand Anything to report here about status? Thanks.

**Comment by u8sand** [comment]
Please see https://github.com/nih-cfde/c2m2-assessment/pull/4 linked. Blocked on updated table of descriptions.

**Comment by RLC-DCPPC** [comment]
Hi @u8sand , is this still blocked?

**Comment by u8sand** [comment]
As far as I know this was addressed. I had updated the metric identifiers and vocabularies according to the spreadsheet and the branch has since been merged.
