### ISSUE TITLE
Curate the initial metrics vocabulary table

### ISSUE THREAD

**Issue by lliming** [nih-cfde/c2m2-assessment#5]
Before the first submission that ingests an initial vocabulary table in Deriva (as described in https://github.com/nih-cfde/cfde-deriva/issues/310), we need to first review a draft table (in a Google Sheet) so we reach agreement on (a) which metrics are going to be reported by the assessment tool, and (b) what their table entries should look like so it is included in the first submission and we don't have to manually fix things later.  A first cut at the table is here:

https://docs.google.com/spreadsheets/d/1VZWkKwvJ0AdgUThvKU7NVhWigtvKjF0aXe9ywSTlfxc/edit#gid=0

I think Amanda needs write access to this sheet.  Or, we'll need to make a copy that's used for this issue.

**Comment by u8sand** [comment]
@lliming I will happily grant edit requests as necessary

**Comment by lliming** [comment]
@ACharbonneau Do you have access to the google sheet yet? If so, anything to report here about status? Thanks.

**Comment by ACharbonneau** [comment]
yup. I did a bunch of curation a week or two ago. Sorry i didn't see this notification until just now.

**Comment by u8sand** [comment]
The sheet is done, and has been reflected in the code.
