### ISSUE TITLE
data breakdown and metadata connectivity numbers do not match on staging

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/c2m2-assessment#6]
I noticed an inconsistency with the FAIR data on the most recent [submission to staging](https://app-staging.nih-cfde.org/dcc_review.html?catalogId=291)

The table _correctly_ says that all 213,123 files have subjects, but the graph _incorrectly_ says that 0 files have subjects.

Also, the table says that 22K subjects have files, but the graph says that 0 subjects have files.

![177643138-56539f53-150d-4dd1-b335-44787f1270cc](https://user-images.githubusercontent.com/7544197/177647354-14dcba08-f85c-49f7-b6a0-03b34e92e8bd.png).

Replaces https://github.com/nih-cfde/dashboard/issues/138

**Comment by raynamharris** [comment]
from @karlcz 

- the actual submission has an empty `file_describes_subject` TSV file, which is what the fair metric is reporting as 0
- the portal does an ETL that imputes associations here based on `file_descibes_biosample` -- `biosample` -- `biosample_from_subject` to give a more consistent search UI, so this table does not look empty in the actual portal catalog
- the review page (which predates the fair metric workflow) seems to be mixing results of querying the live catalog with the precomputed metrics, leading to this inconsistency

So maybe these are "works as designed" for the current release. maybe future work could prune inconsistencies

**Comment by jonathancrabtree** [comment]
It looks like @karlcz has already confirmed my first guess on this, which is that the two tables are not computing those counts in the same way. I added the original version of the "Data Total" and "Data Breakdown" tables, using queries of the live catalog (as Karl describes) to generate those numbers. I believe the FAIR metrics were done completely independently (and perhaps only later incorporated onto this specific page?) which--in addition to the fact that it's data-dependent--may explain why nobody noticed the inconsistency until now.

**Comment by raynamharris** [comment]
I created two new data submissions that confirm Karl and Jonathan's suspicions.  

[293](https://app-staging.nih-cfde.org/dcc_review.html?catalogId=293) is a random data set with complete  file_describes_subject and file_describes_biosample files. [294](https://app-staging.nih-cfde.org/dcc_review.html?catalogId=294) is the same data submission except that  file_describes_subject is empty and file_describes_biosample was cut in half. 

The numbers in the data table and graph match in 293 but not 294.

![Screen Shot 2022-07-07 at 12 00 03 AM](https://user-images.githubusercontent.com/7544197/177837254-7d1f84ac-3b8b-452c-95d0-09da0b7df4db.png)

**Comment by raynamharris** [comment]
in summary, the numbers in the table and graph are different because they are calculated differently. If users notice inconsistencies, the cause is likely due to empty c2m2 csv files. We could update the user documentation but nothing about the assessment needs to change :)
